name: 'Get PR Details'
description: 'Gets important PR details such as the URL, and requestor'
author: 'Benjamin Maynard'
outputs:
  prurl:
    description: 'The URL of the PR'
  prid:
    description: 'The ID of the PR'
  prcreator:
    description: 'The creator of the PR'
  prmerged:
    description: 'The PR Merge Status'
  praction:
    description: 'The PR Action' 
  prbranch:
    description: 'The PR head branch' 
  prheadsha:
    description: 'The PR head SHA' 
  reponame:
    description: 'The repo name' 
runs:
  using: 'docker'
  image: 'Dockerfile'
